<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\ModelNewsletter;

/**
 * ModelNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelNewsletterRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:ModelNewsletter')->findAll();
    }

    public function save(ModelNewsletter $modelNewsletter){
        $this->entityManager->persist($modelNewsletter);
        $this->entityManager->flush();
    }

    public function delete(ModelNewsletter $modelNewsletter){
        $this->entityManager->remove($modelNewsletter);
        $this->entityManager->flush();
    }
}
