<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\Newsletter;
use MarketingBundle\Entity\NewsletterMenu;

/**
 * NewsletterMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterMenuRepository extends \Doctrine\ORM\EntityRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }
    
    public function findbyNewsletter(Newsletter $newsletter){
        return $this->entityManager->getRepository('MarketingBundle:NewsletterMenu')->findBy(['newsletter' => $newsletter]);
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:NewsletterMenu')->findAll();
    }

    public function save(NewsletterMenu $newsletterMenu){
        $this->entityManager->persist($newsletterMenu);
        $this->entityManager->flush();
    }

    public function delete(NewsletterMenu $newsletterMenu){
        $this->entityManager->remove($newsletterMenu);
        $this->entityManager->flush();
    }
}
