<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\NewsletterBlockType;

/**
 * BlockTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterBlockTypeRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:NewsletterBlockType')->findAll();
    }
    
    public function save(NewsletterBlockType $newsletterBlockType){
        $this->entityManager->persist($newsletterBlockType);
        $this->entityManager->flush();
    }

    public function delete(NewsletterBlockType $newsletterBlockType){
        $this->entityManager->remove($newsletterBlockType);
        $this->entityManager->flush();
    }

}
