<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\NewsletterProduct;

/**
 * NewsletterProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterProductRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }
    
    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:NewsletterProduct')->findAll();
    }

    public function save(NewsletterProduct $newsletterProduct){
        $this->entityManager->persist($newsletterProduct);
        $this->entityManager->flush();
    }

    public function delete(NewsletterProduct $newsletterProduct){
        $this->entityManager->remove($newsletterProduct);
        $this->entityManager->flush();
    }
}
