<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\NewsletterBlock;

/**
 * NewsletterBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterBlockRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:NewsletterBlock')->findAll();
    }

    public function save(NewsletterBlock $newsletterBlock){
        $this->entityManager->persist($newsletterBlock);
        $this->entityManager->flush();
    }

    public function delete(NewsletterBlock $newsletterBlock){
        $this->entityManager->remove($newsletterBlock);
        $this->entityManager->flush();
    }
}
