<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityNotFoundException;
use MarketingBundle\Entity\Provider;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    /**
     * @return Provider
     * @throws EntityNotFoundException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getDefault(){
        $q = $this->entityManager->createQueryBuilder();
        $q->select('p')
            ->from('MarketingBundle:Provider', 'p')
            ->where('p.isDefault = :isDefault')
            ->setParameters([
                'isDefault' => true,
            ]);

        $provider = $q->getQuery()->getOneOrNullResult();

        if (null === $provider) {
            throw new EntityNotFoundException(sprintf('Provider "%s" not found.', 'default'));
        }

        return $provider;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:Provider')->findAll();
    }

    public function save(Provider $provider){
        $this->entityManager->persist($provider);
        $this->entityManager->flush();
    }

    public function delete(Provider $provider){
        $this->entityManager->remove($provider);
        $this->entityManager->flush();
    }
}
