<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\Shop;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:Shop')->findAll();
    }

    public function save(Shop $shop){
        $this->entityManager->persist($shop);
        $this->entityManager->flush();
    }

    public function delete(Shop $shop){
        $this->entityManager->remove($shop);
        $this->entityManager->flush();
    }
}
