<?php

namespace MarketingBundle\Repository;
use Doctrine\ORM\EntityManager;
use MarketingBundle\Entity\ShopConfiguration;

/**
 * ShopConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopConfigurationRepository
{
    private $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findAll(){
        return $this->entityManager->getRepository('MarketingBundle:ShopConfiguration')->findAll();
    }

    public function save(ShopConfiguration $shopConfiguration){
        $this->entityManager->persist($shopConfiguration);
        $this->entityManager->flush();
    }

    public function delete(ShopConfiguration $shopConfiguration){
        $this->entityManager->remove($shopConfiguration);
        $this->entityManager->flush();
    }
}
