security:
    providers:
        chain_provider:
            chain:
                providers: [user_repository]
        user_repository:
            id: faulty.repository.user

    encoders:
        #Unicorn\Bundle\UserBundle\Entity\User: sha512
        FaultyProductBundle\Entity\User: sha512

    #ips: [37.58.179.12, ]
    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [176.145.237.59, 37.58.179.194, 127.0.0.1, 192.168.1.7] }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [176.145.237.59, 37.58.179.194, 127.0.0.1, 192.168.1.7] }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/marketing, roles: ROLE_USER }
        - { path: ^/moderate_review, roles: ROLE_USER }
        - { path: ^/picture_crawler, roles: ROLE_USER }
        - { path: ^/faulty, roles: ROLE_USER }
        - { path: ^/shop, roles: ROLE_USER }
        - { path: ^/mail_signature, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [176.145.237.59, 37.58.179.194, 127.0.0.1, 192.168.1.7] }
        - { path: ^/, roles: ROLE_NO_ACCESS }

    role_hierarchy:
        ROLE_NEWSLETTER:        ROLE_USER
        ROLE_MODERATE_REVIEW:   ROLE_USER
        ROLE_FAULTY:            ROLE_USER
        ROLE_MAIL_SIGNATURE:    ROLE_USER
        ROLE_SHOP:              ROLE_USER
        ROLE_ADMIN:             [ROLE_NEWSLETTER, ROLE_MODERATE_REVIEW, ROLE_FAULTY, ROLE_MAIL_SIGNATURE, ROLE_SHOP]
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        user_secured_area:
            pattern:    ^/
            anonymous: ~
            context: user
            form_login:
                provider: user_repository
                login_path: /user/login
                check_path: /user/login
            logout:
                path:   /user/logout
                target: /
