services:
#    moderate_review.example:
#        class: ModerateReviewBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    moderate_review.repository.order:
        class: ModerateReviewBundle\Repository\OrderRepository
        arguments: ["@doctrine.dbal.cm_connection"]

    moderate_review.configure_menu_listener:
        class: ModerateReviewBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: unicorn.user.main_menu_logged, method: onMainMenuLoggedConfigure }
        arguments: ["@service_container"]
