<?php

namespace Proxies\__CG__\MarketingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Shop extends \MarketingBundle\Entity\Shop implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'id', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'name', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'address1', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'address2', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'postalCode', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'city', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'country', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'mail', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'phone', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'textFooter', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'shopConfiguration'];
        }

        return ['__isInitialized__', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'id', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'name', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'address1', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'address2', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'postalCode', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'city', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'country', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'mail', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'phone', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'textFooter', '' . "\0" . 'MarketingBundle\\Entity\\Shop' . "\0" . 'shopConfiguration'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Shop $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getShopConfigurationByName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopConfigurationByName', [$name]);

        return parent::getShopConfigurationByName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress1($address1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress1', [$address1]);

        return parent::setAddress1($address1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress1', []);

        return parent::getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', [$address2]);

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', []);

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getTextFooter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextFooter', []);

        return parent::getTextFooter();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextFooter($textFooter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextFooter', [$textFooter]);

        return parent::setTextFooter($textFooter);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopConfiguration', []);

        return parent::getShopConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopConfiguration($shopConfiguration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopConfiguration', [$shopConfiguration]);

        return parent::setShopConfiguration($shopConfiguration);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelNewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelNewsletter', []);

        return parent::getModelNewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelNewsletter($modelNewsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelNewsletter', [$modelNewsletter]);

        return parent::setModelNewsletter($modelNewsletter);
    }

}
