<?php

namespace Proxies\__CG__\MarketingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NewsletterProduct extends \MarketingBundle\Entity\NewsletterProduct implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'id', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'position', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'idPrestashopProduct', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'idPrestashopDefaultImage', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'title', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'price', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'priceOld', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'link', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'picture', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'description', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'cssTitle', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'filePicture', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'updatedAt', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'search', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'searchButton', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'newsletterBlock'];
        }

        return ['__isInitialized__', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'id', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'position', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'idPrestashopProduct', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'idPrestashopDefaultImage', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'title', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'price', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'priceOld', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'link', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'picture', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'description', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'cssTitle', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'filePicture', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'updatedAt', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'search', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'searchButton', '' . "\0" . 'MarketingBundle\\Entity\\NewsletterProduct' . "\0" . 'newsletterBlock'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NewsletterProduct $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isUploadFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUploadFile', []);

        return parent::isUploadFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsletterBlock($newsletterBlock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsletterBlock', [$newsletterBlock]);

        return parent::setNewsletterBlock($newsletterBlock);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsletterBlock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsletterBlock', []);

        return parent::getNewsletterBlock();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPrestashopProduct($idPrestashopProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPrestashopProduct', [$idPrestashopProduct]);

        return parent::setIdPrestashopProduct($idPrestashopProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPrestashopProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPrestashopProduct', []);

        return parent::getIdPrestashopProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceOld($priceOld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceOld', [$priceOld]);

        return parent::setPriceOld($priceOld);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceOld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceOld', []);

        return parent::getPriceOld();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function getSearch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearch', []);

        return parent::getSearch();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearch($search)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearch', [$search]);

        return parent::setSearch($search);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPrestashopDefaultImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPrestashopDefaultImage', []);

        return parent::getIdPrestashopDefaultImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPrestashopDefaultImage($idPrestashopDefaultImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPrestashopDefaultImage', [$idPrestashopDefaultImage]);

        return parent::setIdPrestashopDefaultImage($idPrestashopDefaultImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilePicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilePicture', []);

        return parent::getFilePicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilePicture($filePicture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilePicture', [$filePicture]);

        return parent::setFilePicture($filePicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssTitle', []);

        return parent::getCssTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssTitle($cssTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssTitle', [$cssTitle]);

        return parent::setCssTitle($cssTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchButton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchButton', []);

        return parent::getSearchButton();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchButton($searchButton)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchButton', [$searchButton]);

        return parent::setSearchButton($searchButton);
    }

}
